export const UPDATE_RIDE_DETAIL = 'UPDATE_RIDE_DETAIL';
export const UPDATE_RIDE_DETAIL_FIRST_RIDE = 'UPDATE_RIDE_DETAIL_FIRST_RIDE';
export const UPDATE_RIDE_DETAIL_RETURN_RIDE = 'UPDATE_RIDE_DETAIL_RETURN_RIDE';
export const CHANGE_RIDE_INFO_TYPE = 'CHANGE_RIDE_INFO_TYPE';
export const RESET_RIDE_DETAIL = 'RESET_RIDE_DETAIL';

export const CHANGE_BOOKING_STEP = 'CHANGE_BOOKING_STEP';

export const UPDATE_VEHICLE_DETAIL = 'UPDATE_VEHICLE_DETAIL';

export const SET_JWT = 'SET_JWT';

export const UPDATE_MY_ACCOUNT_USER_PROFILE = 'UPDATE_MY_ACCOUNT_USER_PROFILE';
export const ADD_SAVE_LOCATION = 'ADD_SAVE_LOCATION';
export const EDIT_SAVE_LOCATION = 'EDIT_SAVE_LOCATION';
export const DELETE_SAVE_LOCATION = 'DELETE_SAVE_LOCATION'